name: Compile

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@86af42dcf465915896671903fcdec3e01a492e87

      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: -no-color -q
          annotate: warning
